### ISSUE TITLE
scp_send doesn't transfer entire file for all hosts, doesn't throw exceptions

### ISSUE THREAD

**Issue by mannyreds11** [ParallelSSH/parallel-ssh#226] opened 2020-09-24 14:08 UTC
### Bug reports

__Steps to reproduce:__

```
client = ParallelSSHClient(hosts, config['ssh']['username'], pkey=os.path.expanduser(credentials['opc_id_rsa_private']['path']))
outputs = client.scp_send(source, destination)
joinall(outputs, raise_error=True)
```

__Expected behaviour:__ [What was expected to happen.]
```
[opc@host1 tmp]$ ls -ltrh file.tar.gz
-rw-r--r-- 1 opc opc 7.7M Sep 24 04:51 file.tar.gz

[opc@host2 tmp]$ ls -ltrh file.tar.gz
-rw-r--r-- 1 opc opc 7.7M Sep 24 04:51 file.tar.gz

[opc@host1 tmp]$ md5sum file.tar.gz
727a5feac278457496376bee7583f8da  file.tar.gz

[opc@host2 tmp]$ md5sum file.tar.gz
727a5feac278457496376bee7583f8da  file.tar.gz
```

__Actual behaviour:__ [What actually happened.]
```
[opc@host1 tmp]$ ls -ltrh file.tar.gz
-rw-r--r-- 1 opc opc 7.7M Sep 24 04:51 file.tar.gz

[opc@host2 tmp]$ ls -ltrh file.tar.gz
-rw-r--r-- 1 opc opc 7.5M Sep 24 04:51 file.tar.gz

[opc@host1 tmp]$ md5sum file.tar.gz
727a5feac278457496376bee7583f8da  file.tar.gz

[opc@host2 tmp]$ md5sum file.tar.gz
00985c4c1919cb8275883da865bd72b3  file.tar.gz
```

__Additional info:__ [Include version of ``ssh2-python`` and/or ``paramiko`` and any other relevant information.]
```
➜  ~ pip3 freeze | grep "parallel-ssh\|ssh2-python\|paramiko"
parallel-ssh==1.13.0
paramiko==2.7.2
ssh2-python==0.20.0
```

**Comment by pkittenis** [comment] 2020-09-27 13:13
Thanks for the interest and report, will try to replicate.

**Comment by pkittenis** [comment] 2020-10-04 13:02
Unable to reproduce as of yet.

[Test case](https://github.com/ParallelSSH/parallel-ssh/blob/scp_send_copy_args/tests/native/test_parallel_client.py#L1356-L1403) is transferring three 8MB files to three local servers and checking checksum.

Have not seen a failure with dozens of multiple runs. This is with OpenSSH server 8.1. Error handling for SCP is the same as any other channel and there are multiple failure test cases for channel error handling.

If can reproduce reliably, can you please enable debug logging and post output:

```
from logging import DEBUG
from pssh.utils import logger, enable_logger

enable_logger(logger, DEBUG)

cmds = client.scp_send(<..>)
joinall(cmds, raise_error=True)
```

**Comment by ThePhunny** [comment] 2020-11-03 23:37
I think I can reproduce this and I have the logs you asked for.
`Make client request for host 20.51.122.117, (host_i, host) in clients: False
Connecting to 20.51.122.117:22
Agent auth failed with ('No identities match for user %s', b'lraab')continuing with other authentication methods
Trying to authenticate with identity file /Users/lraab/.ssh/id_rsa
Authentication with identity file /Users/lraab/.ssh/id_rsa failed, continuing with other identities
Trying to authenticate with identity file /Users/lraab/.ssh/id_dsa
Authentication with identity file /Users/lraab/.ssh/id_dsa failed, continuing with other identities
Private key auth failed, trying password
Authentication completed successfully - setting session to non-blocking mode
Polling socket with timeout 100
Polling socket with timeout 100
Polling socket with timeout 100
Polling socket with timeout 100
Polling socket with timeout 100
Polling socket with timeout 100
Polling socket with timeout 100
SCP local file /Users/lraab/Downloads/jhinv_stage64.json to remote destination 20.51.122.117:/home/lraab/jhinv_stage64.json
real	0m1.752s
user	0m0.224s
sys	0m0.081s
`
The file on the host:
`-rw-r--r--. 1 lraab lraab 0 Nov  3 23:36 jhinv_stage64.json`

**Comment by pkittenis** [comment] 2020-11-08 12:13
Still cannot reproduce. 

Have seen that the server can delay writing file to disk because of memory caching - the tests have a delay before checking `os.stat` to account for that.

From the library's perspective the SCP transfer is completed successfully, also from debug log above. Cannot see an issue with the library here.

Could also try `copy_file` for an SFTP transfer see if that works better. Same API.

**Comment by pkittenis** [comment] 2020-12-01 18:17
Unable to reproduce.

Debug logging from library shows file was transferred completely and without errors - `SCP local file` line - closing.

If can somehow reproduce, or show an issue with library can be re-opened.

**Closed by pkittenis** 2020-12-01 18:17 UTC
Labels: cannot reproduce

**Comment by wynnw** [comment] 2022-02-16 00:39
I've run into this a bunch today as I've begun using this. It's hard to repro every time, but I've got a path where sending 100mb files to two hosts is missing the last few bytes on just one about 50% of the time. Still investigating, but this is a real issue...

If I add a time.sleep() at the of the data loop in _scp_send I never have the problem, so that's interesting.

**Comment by pkittenis** [comment] 2022-03-01 09:55
Let's track this in #337.
