### ISSUE TITLE
Single-SSH client is not cleaned up properly if it has a _proxy_client connection

### ISSUE THREAD

**Issue by DuTogira** [ParallelSSH/parallel-ssh#292] opened 2021-04-09 18:55 UTC
**Describe the bug**
When dereferencing a native/single ssh connection which has a _proxy_client, the ssh connection is not properly cleaned up. This is mostly benign as long as the client to which the connection was made remains powered on, however, for a use case where the formerly connected _proxy_client is rebooted, garbage _proxy_clients build up. This can lead to memory corruption, and after enough reboots of the _proxy_client, can cause segfaults.

**To Reproduce**

1. Example code that produces error.
    Note that I cannot upload a .py, so below find the full python file:

```
import time
import os
from dlipower import PowerSwitch
from pssh.clients import SSHClient
from requests.exceptions import ReadTimeout
from ruamel.yaml import YAML

yaml = YAML()

class Client:
    # Note that user is not important, but I use root because it is the only universal user
    def __init__(self, ip, user="root"):
        super().__init__(ip, user)
        self.ip = ip
        self.user = user
        self.ssh = None
        self.logfunc = print

    def connect(self):
        self.ssh = SSHClient(**self.get_connect_kwargs())

    def close(self):
        # Dereferencing the ssh client should be all I need to clean up properly, as disconnect()
        # is called by the ssh client destructor method AND exit method.
        # However, if ssh client has a _proxy_client, that proxy client is NOT dereferenced,
        # and is therefore not cleaned up
        
        # Note that if I add the below commented-out line, everything works as intended
        # self.ssh._proxy_client = None
        
        self.ssh = None

    def get_connect_kwargs(self):
        return {
            "host": str(self.ip),
            "user": self.user,
            "pkey": "CLIENT_KEY_PATH",
            "keepalive_seconds": 0
        }

    def get_file(self, remotepath, localpath):
        output = self.ssh.copy_remote_file(remotepath, localpath)
        self.logfunc("")

        return output


class ProxyClient(Client):
    def __init__(self, client, user="root"):
        self.client = client
        super().__init__("client", user)

    def get_connect_kwargs(self):
        kwargs = super().get_connect_kwargs()
        kwargs.update({
            "pkey": "PROXY_CLIENT_KEY_PATH",
            "proxy_host": self.client.ip,
            "proxy_user": self.client.user,
            "proxy_pkey": "CLIENT_KEY_PATH"
        })
        return kwargs


class MySSHClient:

    def __init__(self, ip):
        self.ip = ip
        self.client = Client(ip=ip)
        self.proxy_client = ProxyClient(client=self.client)
        self.connect()

    def connect(self):
        self.client.connect()
        self.proxy_client.connect()

    def close(self):
        self.client.close()
        self.proxy_client.close()


# Note that in this case I am using a power switch from digital loggers, but you may need to
# replace this with whatever interface you might have to a networked PDU
# The reason for using a PDU is so that we can close the ssh connection before rebooting the
# unit, as opposed to doing a run_command() of `sudo reboot` or some other arcane strategy.
# This gives the pssh library the benefit of the doubt in having every opportunity to clean up
# properly before the client is rebooted.
class PSwitch:
    def __init__(self, switch_ip, user, pwd, port):
        self.switch_ip = switch_ip
        self.user = user
        self.pwd = pwd
        self.port = port
        self.switch = None

    def cycle_power(self):
        """
        Power cycle the outlet
        """
        # connect to power switch
        # Give up to 3 retries in establishing a connection to the switch
        retries = 3
        for retry in range(retries):
            try:
                self.switch = PowerSwitch(
                    hostname=self.switch_ip, userid=self.user, password=self.pwd,
                    cycletime=0)
                break
            except ReadTimeout as e:
                if retry == retries - 1:
                    raise e
                else:
                    pass
        self.switch.cycle(outlet=self.port)


def try_ping_unit(client_ip, ping_timeout=60):
    """
    Try to ping our client to verify that it is reachable.
    Raise a TimeoutError if we cannot ping the client within our ping timeout

    :param ping_timeout: How long (in seconds) to try pinging before raising a TimeoutError
                         (60s default)
    """
    start_time = time.time()
    timeout = time.time() + ping_timeout
    while time.time() < timeout:
        if os.system("ping -c 1 %s" % client_ip) == 0:
            now = time.time()
            mins = int(now - start_time) // 60
            seconds = int(now - start_time) // max(mins, 1)
            print("Client pingable after %sm %ss" % (mins, seconds))
            break
    if time.time() > timeout:
        raise TimeoutError("Client unpingable after %s seconds" % ping_timeout)


def read_yaml(yaml_path):
    """Loads yaml from localhost, returns data"""
    with open(yaml_path, "r") as config:
        data = yaml.load(config)

    return data


if __name__ == "__main__":
    client_ip = ""  # provide an ip address to connect to
    local_yaml = "/Path/to/save/file.yaml"  # provide some yaml file
    power_switch = PSwitch(switch_ip="ip.of.power.switch", user="username", pwd="1234", port="4")
    ssh_connection = MySSHClient(client_ip)
    for i in range(5):
        print("Running cycle %s" % i)
        print("Closing ssh connection")
        ssh_connection.close()
        print("SSH connection closed")
        power_switch.cycle_power()
        print("Switch cycled")
        try_ping_unit(client_ip)
        ssh_connection = MySSHClient(client_ip)
        print("Connection re-established")
        ssh_connection.client.get_file("PATH/to/remote/file.yaml", local_yaml)
        print("Got remote file")
        # Note that the below read operation is fatal the second we open the downloaded file
        # AFTER a power cycle
        loaded_yaml = read_yaml(local_yaml)
        print("Loaded remote file")
    pass

```

2. Stack trace or error messages.
Running cycle 1 (Note that this is actually the second iteration)
Closing ssh connection
SSH connection closed
2021-04-09 10:37:48,578: tunnel.py: 180: ERROR: Forward socket read error: [Errno 9] Bad file descriptor
Switch cycled
PING 10.1.15.242 (10.1.15.242): 56 data bytes
--- 10.1.15.242 ping statistics ---
1 packets transmitted, 0 packets received, 100.0% packet loss
PING 10.1.15.242 (10.1.15.242): 56 data bytes
--- 10.1.15.242 ping statistics ---
1 packets transmitted, 0 packets received, 100.0% packet loss
PING 10.1.15.242 (10.1.15.242): 56 data bytes
64 bytes from 10.1.15.242: icmp_seq=0 ttl=62 time=49.651 ms
--- 10.1.15.242 ping statistics ---
1 packets transmitted, 1 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 49.651/49.651/49.651/0.000 ms
Client pingable after 0m 22s
2021-04-09 10:39:37,081: single.py: 489: INFO: Copied local file /path/to/local/file.yaml from remote destination 10.1.15.242:/path/to/remote/file.yaml
Got remote file
Python(3534,0x1199c5e00) malloc: *** error for object 0x7fb36d4a04f0: pointer being freed was not allocated
Python(3534,0x1199c5e00) malloc: *** set a breakpoint in malloc_error_break to debug
Process finished with exit code 6

**Expected behavior**
I should be able to disconnect from and reconnect to ssh clients smoothly, and no behavior should change based on whether or not I reboot the client. I expect the SSH connection to be completely cleaned up, even if I am using a proxy_client.
Note that I don't see this behavior if I don't reboot the client.

**Actual behaviour**
The proxy client is disconnected from, but is not dereferenced, and is therefore not cleaned up by the python garbage collector. This leaves open tunnels and other garbage objects in reference, which causes issues when reconnecting to the proxy_client, eventually leading to segfaults

**Additional information**
Dependencies:
requests>=2,<3
ruamel.yaml==0.15.37
ssh-python==0.9.0  # Pinning ssh-python version to prevent compatibility issues with parallel-ssh
ssh2-python==0.22.0  # Pin for parallel-ssh
parallel-ssh==2.5.4
dlipower==1.0.176 # Lib for controlling digital loggers web power switch

Note: 
I have been able to fix this issue by making a change to my client close() logic as outlined above (see class Client, def close). I should not have had to dig for this fix. The _proxy_client should be dereferenced in native/single.py in the disconnect() function, rather than having disconnect() of the main client call disconnect() of the _proxy_client (which does NOT dereference the _proxy_client)

Note2: This issue is suppressed if you do not disable the keepalive timeout. This is a bad solution though because:
1. Using a keepalive timeout interferes with multiprocessing. If I spawn an ssh connection in a child-thread, the keepalive timeout tries to retain a connection to the parent process, which is not listening. This means that the child's SSH connection lasts only the length of the keepalive.
2. While the OS will clean up the tunnels etc which pssh failed to clean once the keepalive timeout is reached (post dereferencing the ssh connection), you have a window between the dereferencing and the keepalive timeout being reached within which this issue could still be reproduced. Assuming the keep-alive saves your program and cleans up, you can still observe the below message in logs without much context as to why the error is thrown:
2021-04-09 10:37:48,578: tunnel.py: 180: ERROR: Forward socket read error: [Errno 9] Bad file descriptor

**Comment by DuTogira** [comment] 2021-04-09 19:32
I'd be happy to put up the pull request to fix this issue myself, but I don't currently have permission to create a new remote branch in this project.

**Comment by pkittenis** [comment] 2021-04-12 09:44
Thanks for the interest.

The bug report does not look valid. Proxy client does not need dereferencing if the client using it is out of scope. An object belonging only to an out of scope object is itself out of scope by definition.

The issue is with your code. It is calling connect and close twice on the same client via the round-about subclassing, which is not needed, while keeping alive two references to the same object.

```
class MySSHClient:

    def __init__(self, ip):
        self.ip = ip
        self.client = Client(ip=ip)
        self.proxy_client = ProxyClient(client=self.client)
        self.connect()

    def connect(self):
        self.client.connect()
        self.proxy_client.connect()

    def close(self):
        self.client.close()
        self.proxy_client.close()
```

Why have this? All `ProxyClient` is doing is passing a reference to Client, which is just SSHClient. Just use `SSHClient` directly. The effect is two SSHClient objects are created with one going out of scope immediately by the call to connect from proxyclient. Code then tries to close a non-existing client with an old reference. Not surprising this does not work well.

Limit your code to a single use of the `SSHClient` directly and try to reproduce. If you can, then provide a minimal amount of code to reproduce that can be used in a test.

**Comment by pkittenis** [comment] 2021-04-12 10:06
Closing as invalid. Can open new issue with minimal code to reproduce as above.

**Closed by pkittenis** 2021-04-12 10:06 UTC
Labels: invalid

**Comment by DuTogira** [comment] 2021-04-12 16:10
The use case here is that I have (for security reasons), one device with an externally exposed ip, and one device which is networked to the exposed device via an internal tunnel. 
Basically, i need: 
1) A regular ssh connection to the externally exposed device
2) An ssh connection to the internal device which is made through the external device.

I absolutely need both SSH connections, so I can't limit my code to just one connection either to the internal device or the external.

I understand that passing the first client as an arg to the proxy client may not be best practice, I can improve that and instead only pass to the proxy_client the attributes which I need (ip and username of the original client).

**Comment by pkittenis** [comment] 2021-04-12 16:52
You only need `SSHClient(<ip>, proxy_host='proxy', proxy_user, proxy_pkey, <..>)` to use proxies. Making a separate client just to the proxy does not do what you want.

The SSHClient itself manages the proxy connection. Client code just needs to configure it.
