### ISSUE TITLE
Tracking multiple hosts and commands

### ISSUE THREAD

**Issue by chopraaa** [ParallelSSH/parallel-ssh#173] opened 2019-05-15 23:10 UTC
I'm passing a list of hosts, and a list of commands to be executed on those hosts but I'm running into issues tracking these.

How would I go about keeping track of which host executed which command? If you run two different commands on a host, a) the hostname gets a suffix attached to it, and b) it's not possible to get which command threw the error.

I tried to follow the docs (there's also a typo in there) [here](https://parallel-ssh.readthedocs.io/en/latest/quickstart.html#retrieving-last-executed-commands): 

```
client.run_command('uname')
output = {}
for i, host in enumerate(hosts):
    cmd = self.cmds[i]
    client.get_output(cmd, output)
    print("Got output for host %s from cmd %s" % (host, cmd))
```

Is it possible to get the command and hostname without iterating through this? I'm using the `stdout`, `stderr` generator to print the output but I'd like to include other information as well like:

```
{
    "uname": [
        "127.1.1.1": {
            "stdout": "Linux",
            "stderr": "",
            "exception": "",
        },
        "127.1.1.2": {
        }
    ]
}  
```

Also, it seems that the [Google group](https://groups.google.com/forum/#!forum/parallelssh) doesn't work anymore.

Thanks!

**Comment by pkittenis** [comment] 2019-05-20 07:59
Hi there,

What is the code being used and what is the issue exactly? De-duplication of hosts happens only when there are multiple identical hosts in host list. Host output will contain output for the command that was executed. Since `run_command` takes a single command, any output from it will be for that cmd. Do not understand what the issue is.

**Comment by chopraaa** [comment] 2019-05-20 08:17
> De-duplication of hosts happens only when there are multiple identical hosts in host list. 

Yes, that's what I'm doing. I'm running multiple scripts against hosts and to speed things up, I'm running 2 commands instead of 1, which is why there's duplication.

Since I'm running a lot of commands against multiple hosts, I want to be able to get _which command was run_ on that host, along with the output of that command but I'm not able to do this.

Here's the code I'm using:

```
        def _run_command(command, args_var=self.remote["remote_scripts"]):
            """Run a command remotely using arguments passed
            
            Keyword arguments:
            command (string) -- command to run on ssh_conn obj
            args_var (string) -- args to pass to command for printing
            """
            script_ex = ssh_conn.run_command(command, host_args=args_var)

            ssh_conn.join(script_ex)

            for host, host_output in script_ex.items():
                for line in host_output.stdout:
                    log.debug(f"[HOST {host}] [STDOUT] {line}")
                for line in host_output.stderr:
                    log.error(f"[HOST {host}] [STDERR] {line}")

                if host_output.exception is not None:
                    log.error(f"[HOST {host}] [EXCEPT] {host_output.exception}")
```

```
_run_command(command="%s", args_var=self.remote["remote_commands"])
```

**Comment by pkittenis** [comment] 2019-05-20 09:13
* Code above shows `run_command(command)`. Command executed is always `command`.
* Command being run on identical hosts using `run_command(command)` is always `command`. Differentiating between the same command being run on the same host multiple times does not make sense - they're always going to be the same.

Why doesn't the code above use the command as it used to call `run_command`?

```
                if host_output.exception is not None:
                    log.error(f"Command executed is {command}")
                    log.error(f"[HOST {host}] [EXCEPT] {host_output.exception}")
```

Does that not show the command executed that had error?

**Comment by chopraaa** [comment] 2019-05-20 09:44
Oh yes, I can't believe I missed it. 😦 

Also, they're running on different hosts, not identical hosts. If I run 2 commands separately on the same host, it shows two hostnames `hostname` and `hostname_randomstring`.

**Comment by pkittenis** [comment] 2019-05-21 08:23
That is done purposefully, per docs. Since output is currently a dictionary keyed by host (until 2.0), identical hosts need changing to be able to get output for them. Can see the hostname as it was given in `host_output.host` - see `HostOutput` [documentation](https://parallel-ssh.readthedocs.io/en/latest/output.html#pssh.output.HostOutput).

Don't see a code issue here, closing. Google group should be visible even when not signed into google now, apparently this was a recent change to group permissions, so can use that for questions.

**Closed by pkittenis** 2019-05-21 08:23 UTC
