### ISSUE TITLE
Native run command with timeout truncates output  

### ISSUE THREAD

**Issue by parisnps** [ParallelSSH/parallel-ssh#109] opened 2018-03-10 06:20 UTC
**Testcase**: ssh into a host 'x' and cat a file of ~ 6000 lines
    failure: when we add timeout in run_command
    success: when we remove timeout 

**Possible Contributing Factor**: ssh via wan link with firewall in there [ Local LAN seems to work well ]

_Firewall can be a factor but then it does work without timeout value in run_command or for that matter direct ssh._ _What changes with timeout value on which can impact / truncate output in this case over WAN link [ stable and battle tested ]_ ??

Sample Code:
```

from pprint import pprint
from pssh.utils import enable_host_logger
from pssh.pssh2_client import ParallelSSHClient


hosts=['x']
client = ParallelSSHClient(hosts)
output = client.run_command('cat /tmp/yo', timeout=15)

for host, host_out in output.items():
    try:
        for line in host_out.stdout:
            print 'output',line
        for line in host_out.stderr:
            print 'error',line
    except:
        print 'error'

```

Output: 'error' 

_[ It does read some 500-600 lines and then errors out ]_

Same Code without timeout:

 
```
from pprint import pprint
from pssh.utils import enable_host_logger
from pssh.pssh2_client import ParallelSSHClient


hosts=['x']
client = ParallelSSHClient(hosts)
output = client.run_command('cat /tmp/yo')
timeout=15)

for host, host_out in output.items():
    try:
        for line in host_out.stdout:
            print 'output',line
        for line in host_out.stderr:
            print 'error',line
    except:
        print 'error'
```
Output: As expected  , all 6000 lines in matter of second.

**Comment by pkittenis** [comment] 2018-03-14 12:49
It looks like output generators are not reset after timeout, [as described in documentation](http://parallel-ssh.readthedocs.io/en/latest/advanced.html#join-and-output-timeouts)?

```
from pssh.exceptions import Timeout

for host, host_out in output.items():
    try:
        for line in host_out.stdout:
            print 'output',line
        for line in host_out.stderr:
            print 'error',line
    except Timeout:
        client.reset_output_generators(host_out)
```

Remember, generators only iterate once. Since they raise an exception on timeout, they need to be re-generated to get any new output from them. 

This is done automatically by `join` if used with or without timeout. When only using output generators, the above needs to be done.

**Comment by parisnps** [comment] 2018-03-14 22:25
The only issue I have with that explanation is that timeout should never get hit. The command itself takes 2 sec to execute and even if I put the timeout to 60s, the output gets truncated. Is that also expected behavior, if so, sounds very counter intuitive. 

Thanks.

**Comment by pkittenis** [comment] 2018-03-16 13:47
No, that's not expected. Will try to replicate that, in the existing test there is a timeout never occurs in this scenario.

**Comment by pkittenis** [comment] 2018-04-01 14:32
Hi there,

Have added a test to reproduce the above but see no timeout even with a 10k line file. The client side code used is:

```
output = self.client.run_command('cat %s' % (_file,), timeout=10)
_out = list(output[self.client.hosts[0]].stdout)
```

Where `_file` is a file with 10k lines. Test can be seen [here](https://github.com/ParallelSSH/parallel-ssh/blob/read_no_timeout_file_read/tests/test_pssh_ssh2_client.py#L1232-L1249).

Can you try to reproduce with the following code.

```
for host, host_out in output.items():
        for line in host_out.stdout:
            print 'output',line
        for line in host_out.stderr:
            print 'error',line
```

To be able to see the stack trace of the exception raised. It is possible the socket timeout occurs prior to reading from file, for example if the socket has been closed by firewall/proxy.

Some firewalls will also forcibly close sockets after N seconds of inactivity. A packet capture will show a `FIN` packet being received by the client from the firewall IP if that is the case.

**Comment by pkittenis** [comment] 2018-05-21 15:34
Closing due to lack of reproduction. Please comment with how to reproduce if it is still and issue and will re-open.

**Closed** 2018-05-21 15:34 UTC
Labels: needs_more_info

**Comment by yuki-nishida-exa** [comment] 2019-09-20 23:08
Hello @pkittenis, I am seeing a similar behavior with this issue and would like to understand the behavior better.

Below is what I am trying:
```
client = ParallelSSHClient([<host where script runs>], pool_size=100, timeout=30)
output = client.run_command('docker exec hadoop-namenode hdfs fsck /', 
                            use_pty=False, timeout=30)
results = {}
for host, host_out in output.items():
        host_result = {'stdout': [], 'stderr': []}
        for stream in ['stdout', 'stderr']:
            try:
                for line in getattr(host_out, stream):
                    host_result[stream].append(line)
            except Timeout:
                logger.warn('Stream timeout happened for {} {}'.format(host, stream))
        results[host] = host_result

client.join(output)
```
In my environment `docker exec ... hdfs fsck /` command take a couple second of pause and generates tens of lines to stdout + 1 line to stdout, but it can take longer with hundreds of lines in our prod environment. While the command runs less than 30 secs, the execution above gets Timeout exception with "Stream timeout happened" warning, and stdout in `host_result` turns out to be empty, while stderr gets the expected one line. Also the scheme above works fine - gets stdout/stderr without timeout - for the other commands which give less output.

As you asked in this conversation, I tried running above without `except Timeout` and got the traceback below:
```
Traceback (most recent call last):
... # Omitting the portion of our code
    for line in getattr(host_out, stream):
  File "/opt/exabeam_installer/.env/lib/python2.7/site-packages/pssh/clients/native/single.py", line 364, in read_output_buffer
    for line in output_buffer:
  File "pssh/native/_ssh2.pyx", line 57, in _read_output
pssh.exceptions.Timeout
```

I read your documentation and this issue, but could not understand this behavior. It'd be appreciated if I could get more insight and the recommended way to fix.

**Comment by yuki-nishida-exa** [comment] 2019-09-24 22:18
Follow-up: I opened a new bug report #180 as I have narrowed down the issue happens when stderr gets output earlier than stdout.
