### ISSUE TITLE
ssh-python dependency

### ISSUE THREAD

**Issue by SkegOverren** [ParallelSSH/parallel-ssh#278] opened 2021-01-28 16:57 UTC
_For general questions please use the [mail group](https://groups.google.com/forum/#!forum/parallel-ssh)._

**Describe the bug**
Updating parallel-ssh installation via pypi "suddenly" forces to use ssh-python

**To Reproduce**

1. pip3 install parallel-ssh

**Expected behavior**
Expecting to be able to install parallel-ssh with ssh2-python only.

**Actual behaviour**
Forced to install ssh-python, which doesn't compile for a number of reasons, like heavily depending on external tools and libraries I don't have nor want.
A former installation of parallel-ssh once was absolutely easy, that's why I based a project on it, but now I cannot even re-install parallel-ssh.

**Screenshots**
n/A

**Additional information**
n/A

**Comment by pkittenis** [comment] 2021-01-28 17:59
Thanks for the interest.

From bug report instructions:

> Steps to reproduce the behavior:
> 1. Example code that produces error.
> 2. Stack trace or error messages.

ssh-python is a dependency and provides the same packaging and installation methods as ssh2-python which is also a dependency. Both have been dependencies since [1.12.0](https://github.com/ParallelSSH/parallel-ssh/blob/master/Changelog.rst#1120). Dependencies are required for a library to work.

If installation is not working, code to reproduce error and the error messages from that code will need to be shown.

No error messages, issue with library, or steps to reproduce an issue have been shown - closing.

For help with an issue, raise a report with steps to reproduce it per instructions in bug report template.

See also [Code of Conduct](https://github.com/ParallelSSH/parallel-ssh/blob/master/.github/code_of_conduct.md) and in particular *Using welcoming and inclusive language*.

**Closed by pkittenis** 2021-01-28 17:59 UTC
Labels: invalid
