### ISSUE TITLE
Client object deletion does not close sockets

### ISSUE THREAD

**Issue by ep4sh** [ParallelSSH/parallel-ssh#175] opened 2019-06-17 08:13 UTC
### Directions

Seems like client object has not been deleted

### Bug reports

__Steps to reproduce:__

1. Example code that produces error.

```
            try:
                client = ParallelSSHClient(
                    [host], user=user, pkey=SSH_KEY, timeout=TIMEOUT, num_retries=RETRIES)
                out_kern = client.run_command('uname -r')
                out_lsb_release = client.run_command('cat /etc/redhat-release')
                del client
```

2. Stack trace or error messages.

__Expected behaviour:__ [What was expected to happen.]

__Actual behaviour:__ [What actually happened.]

```
Traceback (most recent call last):
  File "./aws-instances", line 172, in <module>
    main()
  File "./aws-instances", line 73, in main
    facts = remote_facts(ips)
  File "./aws-instances", line 146, in remote_facts
    out_kern = client.run_command('uname -r')
  File "/home/user/do-aws-ec2-facts/aws/lib64/python3.6/site-packages/pssh/clients/native/parallel.py", line 223, in run_command
    greenlet_timeout=greenlet_timeout)
  File "/home/user/do-aws-ec2-facts/aws/lib64/python3.6/site-packages/pssh/clients/base_pssh.py", line 96, in run_command
    self.get_output(cmd, output, timeout=greenlet_timeout)
  File "/home/user/do-aws-ec2-facts/aws/lib64/python3.6/site-packages/pssh/clients/base_pssh.py", line 141, in get_output
    (channel, host, stdout, stderr, stdin) = cmd.get(timeout=timeout)
  File "src/gevent/greenlet.py", line 709, in gevent._greenlet.Greenlet.get
  File "src/gevent/greenlet.py", line 317, in gevent._greenlet.Greenlet._raise_exception
  File "/home/user/do-aws-ec2-facts/aws/lib64/python3.6/site-packages/gevent/_compat.py", line 47, in reraise
    raise value.with_traceback(tb)
  File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
  File "/home/user/do-aws-ec2-facts/aws/lib64/python3.6/site-packages/pssh/clients/native/parallel.py", line 237, in _run_command
    raise ex
  File "/home/user/do-aws-ec2-facts/aws/lib64/python3.6/site-packages/pssh/clients/native/parallel.py", line 233, in _run_command
    use_pty=use_pty, encoding=encoding, timeout=timeout)
  File "/home/user/do-aws-ec2-facts/aws/lib64/python3.6/site-packages/pssh/clients/native/single.py", line 442, in run_command
    channel = self.execute(_command, use_pty=use_pty)
  File "/home/user/do-aws-ec2-facts/aws/lib64/python3.6/site-packages/pssh/clients/native/single.py", line 324, in execute
    channel = self.open_session() if channel is None else channel
  File "/home/user/do-aws-ec2-facts/aws/lib64/python3.6/site-packages/pssh/clients/native/single.py", line 297, in open_session
    wait_select(self.session)
  File "pssh/native/_ssh2.pyx", line 171, in pssh.native._ssh2.wait_select
  File "/home/user/do-aws-ec2-facts/aws/lib64/python3.6/site-packages/gevent/select.py", line 145, in select
    sel_results = _original_select(rlist, wlist, xlist, 0)
ValueError: filedescriptor out of range in select()

```

Growing count of opened file descriptors and error at the end

![image](https://user-images.githubusercontent.com/19505042/59587771-b6807980-90ee-11e9-93e7-784b0a8467da.png)

**Comment by pkittenis** [comment] 2019-06-20 08:18
Hi there,

Thanks for the interest and report. Looks like the single client is not being garbage collected after the parallel client goes out of scope/is deleted. This causes socket to stay in scope and not be closed.

For the above use case, why not use a single, long running client rather than re-creating a new one with a single host each time? The client is parallel in order to support that kind of use.

**Comment by ep4sh** [comment] 2019-06-20 09:03
Hi! Thanks for updates, but there is a lot of hosts, probably my missing when I post the source code, I didn't mention about it:
```
    for host in hosts:
        for user in users:
            try:
                client = ParallelSSHClient(
                    [host], user=user, pkey=SSH_KEY, timeout=TIMEOUT, num_retries=RETRIES)
                out_kern = client.run_command('uname -r')
                out_lsb_release = client.run_command('cat /etc/redhat-release')
.............
# antoher code......
```

**Comment by ep4sh** [comment] 2019-06-21 12:33
When I create SSH connection to ~ 300 server - it works fine
But when connection count over than 1000 - I feel the pain.

**Comment by pkittenis** [comment] 2019-06-23 20:23
What I meant was, the code is only connecting to one host per client:

```
                client = ParallelSSHClient(
                    [host], user=user, pkey=SSH_KEY, timeout=TIMEOUT, num_retries=RETRIES)
```

```[host]``` can contain many hosts, `]host1, host2]` etc. This reduces the number of temporary, and there for total number of sockets required.

**Comment by changhsien** [comment] 2019-08-13 23:29
I think it's caused by this bug - https://groups.google.com/forum/#!topic/parallelssh/u1JFLmERmtU
Basically the "del client" is not disconnecting the socket.  You have to use the work-around to disconnect for now.

But isn't there a 1024 limit for using Python select()?  In newer Python subprocess implementation it's using poll() instead of select().  So if there are more than 1024 active connections, we might hit the select() bug?

**Closed** 2020-08-14 16:16 UTC
Labels: bug, native client

**Comment by vijkaush** [comment] 2020-09-15 06:28
which place in my code I should use this code
for single_client in client.host_clients.values():
             single_client.disconnect()

**Comment by pkittenis** [comment] 2020-09-17 11:21
There is no need for that work around anymore. `ParallelSSHClient` disconnects its clients when the object goes out of scope. To trigger it can `del client`.
