### ISSUE TITLE
The output of run_command is cut off 

### ISSUE THREAD

**Issue by zs0723** [ParallelSSH/parallel-ssh#92] opened 2017-09-27 09:45 UTC
I have a script running on host , the output of the script has thousands of lines,   i found the output is cut off . Should i redirect the output of the script to a file, then download it from host? 
cmd = "python myscript.py"
output = client.run_command(cmd)
client.join(output)
&nbsp;&nbsp;for host in output:
  &nbsp;&nbsp; &nbsp;&nbsp;for line in list(output[host].stdout):
  &nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;print line

**Comment by zs0723** [comment] 2017-09-28 06:18
Yes, i checkout the output, the exit code is 0, The cut off means : The total length of lines of the output is about  3000, but got the result only 1266 lines with run_command('cat <file>'). 
more details:
(1) I got more output with use_pty=False , but the content is also not complete.
(2) The Host is Linux, the ParallelSSHClient script is running on windows 10.
(3)  I use Anaconda  environment
(4)  The code

**Comment by pkittenis** [comment] 2017-09-29 08:57
Hmm, I have not been able to replicate yet.

Here is test code from the above example:

```
from __future__ import print_function

from pssh.pssh_client import ParallelSSHClient

client = ParallelSSHClient(['localhost'])
output = client.run_command('cat big_file.txt')
client.join(output)
stdout = list(output['localhost'].stdout)
# for host in output:
#     for line in list(output[host].stdout):
#         print(line)
print(len(stdout))
```

Output:

`6342`

Lines in file:

`$ cat ~/big_file.txt | wc -l`

`6342`

Using the commented for block and `| wc -l` on the python process has same output.

This is with latest parallel-ssh version and paramiko 2.1 and on Linux, will test Windows later.

Could you attach your own `bigfile.txt` in this issue? Paramiko, the current default ssh client, has some... special.. line parsing code for its output and it may be thinking it has reached the end before it actually has. My big file is a C source code file.

Can you also please confirm which versions of parallel-ssh and paramiko you are using.

**Comment by zs0723** [comment] 2017-10-09 09:09
The issue is not related to content of file. I created any long lines of text file will reproduce the issue.
It seems that my pssh is not correct installed ?
```
$>python
Python 2.7.13 |Anaconda 4.4.0 (64-bit)| (default, May 11 2017, 13:17:26) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import pssh

>>> print pssh.__version__
0+unknown           <<<
>>> import paramiko
>>> print paramiko.__version__
2.1.4
>>> help(pssh)
Help on package pssh:

NAME
    pssh - Asynchronous parallel SSH client library.

FILE
    c:\programdata\anaconda2\lib\site-packages\pssh\__init__.py

DESCRIPTION
    Run SSH commands over many - hundreds/hundreds of thousands - number of servers
    asynchronously and with minimal system load on the client host.

    New users should start with
    :py:func:`pssh.pssh_client.ParallelSSHClient.run_command`

    See also :py:class:`pssh.ParallelSSHClient` and :py:class:mod:`pssh.SSHClient`
    for class documentation.

PACKAGE CONTENTS
    _version
    agent
    constants
    exceptions
    output
    pssh_client
    ssh_client
    utils

DATA
    __version__ = '0+unknown'
    host_logger = <logging.Logger object>
    logger = <logging.Logger object>

VERSION
    0+unknown


>>>
>>>
```

**Comment by pkittenis** [comment] 2017-10-09 16:39
Tested on windows client connecting to Linux host with latest version as well, still cannot reproduce.

```
PS F:\> pip install -U parallel-ssh
<snip>
PS F:\> pip install paramiko==2.1.4
Requirement already satisfied: paramiko==2.1.4 in c:\users\asdf\appdata\roaming\
python\python27\site-packages

PS F:\> python .\lines.py
2122
PS F:\>
```

`lines.py` is as test code pasted previously, with a different file used for `cat`.

I'll give anaconda on windows a try later - I am not the maintainer of that anaconda package and it does not look like it was built correctly (missing version).

Can you try installing latest version from pip from within the conda environment. Pip should be available already, install it with conda if not:

```
conda install pip
pip install -U parallel-ssh
```

Then try your script again.

Can you also please attach one of your test files here in any case. I am sure you can replicate the issue but I cannot so I need a sample file which has been tested to reproduce the error already. All my files are linux built so the tests are not the same.

**Comment by zs0723** [comment] 2017-10-10 01:57
My file has 501002 lines, I have used paramiko library directly, i got expected output. I also found parallel-ssh is not part of anaconda package list yet. Maybe those two things are not compatible.
```
import paramiko
ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh.connect('ip', username='username', password='pwd')
cmd = 'cat /root/a.log'
ssh_stdin, ssh_stdout, ssh_stderr = ssh.exec_command(cmd)
print ssh_stderr.read()
print len(ssh_stdout.readlines())
[a.log](https://github.com/ParallelSSH/parallel-ssh/files/1370306/a.log)

```

**Comment by pkittenis** [comment] 2017-10-12 11:56
Have now tested:

Anaconda on Windows, Python 2.
Anaconda on Windows, Python 3.

Both connecting to Linux host, `cat a.log` as attached above. Here is the `lines.py` script:

```
from __future__ import print_function
from pssh.pssh_client import ParallelSSHClient

host = '<ip>'
client = ParallelSSHClient([host], user='<user>', password='<pass>')
output = client.run_command('cat a.log')
client.join(output)
stdout = list(output[host].stdout)
print(len(stdout))
```

Output:

Python 2

```
(C:\Users\asdf\Miniconda2) C:\>conda install paramiko -y
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment C:\Users\asdf\Miniconda2:

The following NEW packages will be INSTALLED:

    paramiko: 2.1.2-py27_0
    pyasn1:   0.3.7-py27h641112c_0

The following packages will be UPDATED:

    conda:    4.3.27-py27had2ba0d_0 --> 4.3.29-py27h6c1d957_0

pyasn1-0.3.7-p 100% |###############################| Time: 0:00:00 589.40 kB/s
paramiko-2.1.2 100% |###############################| Time: 0:00:00 765.52 kB/s
conda-4.3.29-p 100% |###############################| Time: 0:00:00  17.59 MB/s

(C:\Users\asdf\Miniconda2) F:\>pip install parallel-ssh
<..>

(C:\Users\asdf\Miniconda2) F:\>python lines.py
501002

(C:\Users\asdf\Miniconda2) F:\>python lines.py
501002
```

Python 3:

```
(C:\Users\asdf\Miniconda3) C:\>conda install paramiko
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment C:\Users\asdf\Miniconda3:

The following NEW packages will be INSTALLED:

    paramiko: 2.1.2-py36_0
    pyasn1:   0.3.7-py36h323361c_0

The following packages will be UPDATED:

    conda:    4.3.27-py36h94e4195_0 --> 4.3.29-py36h4f40c76_0

Proceed ([y]/n)? y

pyasn1-0.3.7-p 100% |###############################| Time: 0:00:00   0.00  B/s
paramiko-2.1.2 100% |###############################| Time: 0:00:00   1.00 MB/s
conda-4.3.29-p 100% |###############################| Time: 0:00:00  17.49 MB/s

(C:\Users\asdf\Miniconda3) C:\>pip install parallel-ssh
Collecting parallel-ssh
<..>

(C:\Users\asdf\Miniconda3) F:\>python lines.py
501002

(C:\Users\asdf\Miniconda3) F:\>python lines.py
501002
```

The two runs are with and without a `pty`.

Still cannot reproduce. It is looking like either environmental issue or SSH server configuration related. There is no difference in the code used for output by [paramiko's `exec_command`](https://github.com/paramiko/paramiko/blob/master/paramiko/client.py#L479-L481) and the [code used in parallel-ssh](https://github.com/ParallelSSH/parallel-ssh/blob/master/pssh/ssh_client.py#L266-L267).

There is also no `parallel-ssh` conda package in either the official or conda-forge channels, not sure where your package came from.

I suggest creating a new conda environment and reinstalling as above with parallel-ssh *from pip*. If you can replicate then make a spec list file from that environment (`conda list --explicit > spec-file.txt`) and please paste it here to reproduce that environment. 

Please also test with `ParallelSSHClient(<..>, timeout=120)` to ensure server timeout is not truncating output.

That will at least narrow it down to server configuration if the same environment cannot reproduce the issue. At the moment cannot investigate further without being able to reproduce.

**Comment by zs0723** [comment] 2017-10-13 15:27
Hi pkittenis, Thanks for your help. It still does not work with "timeout=120". I will update here if there is any findings. I think you can close the issue.

**Comment by pkittenis** [comment] 2017-10-18 09:23
I'd still like to understand what is causing this - it's a weird issue, at the least I'd like to confirm it's not an issue in `parallel-ssh`.

Can you please try the following when you get a chance:

```
conda create -n new_env -y
source activate new_env
conda install paramiko -y
pip install --user parallel-ssh
```

And try the script above. If the issue persists, export the environment like so:

```
conda list --explicit > spec-file.txt
```

And attach `spec-file.txt` in this issue. That will make it possible to re-create that exact same environment, including platform. If you have access to the *server's* SSH config (`/etc/ssh/ssh_config`) can you please also attach it here.

Can also try the new client in latest version - `1.2.0` - that was just released. It uses a different SSH library and completely new parsing code.

```
from pssh.pssh2_client import ParallelSSHClient
<rest of code the same>
```

**Comment by pkittenis** [comment] 2017-11-10 16:03
Closing, please re-open with above data if issue can be replicated.

**Closed by pkittenis** 2017-11-10 16:03 UTC
Labels: needs_more_info
